### ISSUE TITLE
Hi, how to get Exposed values ?

### ISSUE THREAD

**Issue by francelwebdev** [nymphaea-v1/quasar-app-extension-q-tel-input#2]
Hi, how to get Exposed values ?

**Comment by nymphaea-v1** [comment]
Hi! You can read about exposed values [here](https://vuejs.org/api/sfc-script-setup.html#defineexpose). To get exposed values, you need to use [Template Refs](https://vuejs.org/guide/essentials/template-refs.html#template-refs). For example:
```js
<template>
    <q-tel-input
      v-model="phone"
      ref="telInputElement"
    >
  </q-tel-input>
</template>

<script setup>
import { ref } from 'vue'

const phone = ref('+995322983035')
const telInputElement = ref() // will be { "country": "GE", "callingCode": "995", "nationalNumber": "322983035" }
</script>
```
